# Site settings
author: Michael Cheng
title: Brown's Data Science Journey
header-img: img/home-bg.png
email: cytmike@gmail.com
copyright_name: Michael Cheng
description: > # this means to ignore newlines until "baseurl:"
  Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cytmike

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
